package views;

import views.directeurScolaire.ListeSallesDirect;

import javax.swing.*;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * cette classe permet de voir le dashboard du chef departement
 */
public class TbordDirecteur extends javax.swing.JFrame {
	Toolkit tk = Toolkit.getDefaultToolkit();
  	 Dimension dimScreen = tk.getScreenSize();

  	    private double largeur = dimScreen.getWidth();
  	    private double longeur = dimScreen.getHeight() - 30;


    /**
     * Creates new form Tborddirecteur
     */
    public TbordDirecteur() {
    	  	
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/GE-logo.png")));
        setSize((int)largeur,(int)longeur);
        this.setLocationRelativeTo(null); 
        this.setTitle("Tableau de bord Directeur");
        
        ListeSallesDirect bd = new ListeSallesDirect();
        content.removeAll();
        content.setLayout(new BorderLayout());
        content.add(bd);
        content.revalidate();
        
        JPanel not=new JPanel();
        not.setPreferredSize(new Dimension(this.getWidth(),100));
        not.setBackground(Color.red);
        JScrollPane sp=new JScrollPane();
       	not.setLayout(new BorderLayout());
        not.add(sp);
        
        JTextArea textArea = new JTextArea();
        textArea.setFont(new Font("Monospaced", Font.BOLD, 15));
        textArea.setEditable(false);
        textArea.setForeground(new Color(0, 0, 0));
        sp.setViewportView(textArea);
        content.add(not, BorderLayout.SOUTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

        JPanel jPanel1 = new JPanel();
        JLabel jLabel1 = new JLabel();
        JPanel jPanel2 = new JPanel();
        JPanel jPanel3 = new JPanel();
        JButton btnSalleLibre = new JButton();
        JButton btnAjouterPlanning = new JButton();
        JButton listEdt = new JButton();
        content = new javax.swing.JPanel();
        JPanel jPanel4 = new JPanel();
        JLabel jLabel2 = new JLabel();
        username = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tableau de bord");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));





        btnSalleLibre.setBackground(new java.awt.Color(0, 102, 204));
        btnSalleLibre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSalleLibre.setForeground(new java.awt.Color(255, 255, 255));
        btnSalleLibre.setText("Lister toutes les salles");
        btnSalleLibre.addActionListener(this::jButton3ActionPerformed);

        btnAjouterPlanning.setBackground(new java.awt.Color(0, 102, 204));
        btnAjouterPlanning.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAjouterPlanning.setForeground(new java.awt.Color(255, 255, 255));
        btnAjouterPlanning.setText("Ajouter un planning");
        btnAjouterPlanning.addActionListener(this::jButton5ActionPerformed);

        listEdt.setBackground(new java.awt.Color(0, 102, 204));
        listEdt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        listEdt.setForeground(new java.awt.Color(255, 255, 255));
        listEdt.setText("Liste des EDT");
        listEdt.addActionListener(this::jButton4ActionPerformed);

        
        JButton btnSalleListe = new JButton();
        btnSalleListe.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		 content.setLayout(new BorderLayout());
        	        content.removeAll();
        	        ListeSallesDirect list = new ListeSallesDirect();
        	        content.add(list);
        	        content.revalidate();
        	}
        });
        btnSalleListe.setText("Lister toutes les salles");
        btnSalleListe.setForeground(Color.WHITE);
        btnSalleListe.setFont(new Font("Tahoma", Font.PLAIN, 18));
        btnSalleListe.setBackground(new Color(0, 102, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3Layout.setHorizontalGroup(
        	jPanel3Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel3Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(btnSalleLibre, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
        				.addComponent(btnAjouterPlanning, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
        				.addComponent(listEdt, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    )));
        jPanel3Layout.setVerticalGroup(
        	jPanel3Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel3Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(btnSalleLibre)
        			.addPreferredGap(ComponentPlacement.RELATED)
                    .addComponent(btnAjouterPlanning)
                    .addPreferredGap(ComponentPlacement.RELATED)
                    .addComponent(listEdt)
                    .addPreferredGap(ComponentPlacement.RELATED)
        ));
        jPanel3.setLayout(jPanel3Layout);

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        contentLayout.setHorizontalGroup(
        	contentLayout.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 756, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
        	contentLayout.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 541, Short.MAX_VALUE)
        );
        content.setLayout(contentLayout);

        jPanel4.setBackground(new java.awt.Color(0, 0, 102));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Connecté en tant Que :");

        username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 102));
        username.setText("RAS");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(username, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(username))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2Layout.setHorizontalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, 257, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(content, GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE)
        				.addComponent(jPanel4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        			.addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(jPanel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addGroup(jPanel2Layout.createSequentialGroup()
        					.addComponent(jPanel4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(content, GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)))
        			.addContainerGap())
        );
        jPanel2.setLayout(jPanel2Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        content.setLayout(new BorderLayout());
        content.removeAll();
        ListeSallesDirect list = new ListeSallesDirect();
        content.add(list);
        content.revalidate();
    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt){
        content.setLayout(new BorderLayout());
        content.removeAll();
        ListeEDT ledt = new ListeEDT();
        content.add(ledt);
        content.revalidate();
    }
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        content.setLayout(new BorderLayout());
        content.removeAll();
        CreateEDTPage edt = new CreateEDTPage();
        content.add(edt);
        content.revalidate();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(() -> new TbordDirecteur().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel content;
    public javax.swing.JLabel username;
}
